name: CNAME Scan

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Query GitHub for CNAME files
      run: |
        PAGE=1
        PER_PAGE=100
        MAX_PAGES=10
        QUERY="filename:CNAME"
        echo "domains:" > results.yml
        while [ $PAGE -le $MAX_PAGES ]; do
          RESPONSE=$(curl -G -H "Accept: application/vnd.github+json" \
                          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                          --data-urlencode "q=$QUERY" \
                          --data-urlencode "per_page=$PER_PAGE" \
                          --data-urlencode "page=$PAGE" \
                          "https://api.github.com/search/code")
          echo $RESPONSE
          echo "$RESPONSE" | jq -r '.items[] | "- domain: \(.repository.full_name)\n  owner: \(.repository.owner.login)\n  repo: \(.repository.name)\n  cname_file_url: \(.url)"' >> results.yml
          TOTAL_COUNT=$(echo "$RESPONSE" | jq '.total_count')
          PAGE=$((PAGE + 1))
          if [ $((PAGE * PER_PAGE)) -ge $TOTAL_COUNT ]; then
            break
          fi
        done

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: cname-scan-results
        path: results.yml